# -*- coding: utf-8 -*-
"""Projeto Individual 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYkxIpp5Xi-yRydZ9cy2XMI0Vr_wh7VX

# Projeto Individual
## Módulo 3 – Relatórios de Progresso

# Importando as bibliotecas necessárias
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Criando o DataFrame"""

data = {
    "Dia": [0, 1, 2, 3, 4, 5, 6],
    "Horas Trabalhadas": [6, 7, 8, 6, 7, 5, 4],
    "Bugs Corrigidos": [3, 2, 1, 4, 3, 2, 1],
    "Tarefas Concluídas": [5, 4, 6, 4, 5, 3, 2]
}

df = pd.DataFrame(data)

"""# Calculando o Total de Horas Trabalhadas"""

total_horas_trabalhadas = df["Horas Trabalhadas"].sum()
total_horas_trabalhadas
print(f"Total de Horas Trabalhadas: {total_horas_trabalhadas}")

"""# Média Diária de Horas Trabalhadas"""

media_horas_trabalhadas = df["Horas Trabalhadas"].mean()
media_horas_trabalhadas
print(f"Média Diária de Horas Trabalhadas: {media_horas_trabalhadas:.2f}")

"""# Calculando o Total de Bugs Corrigidos"""

total_bugs_corrigidos = df["Bugs Corrigidos"].sum()
total_bugs_corrigidos
print(f"Total de Bugs Corrigidos: {total_bugs_corrigidos}")

"""# Calculando a Média Diária de Bugs Corrigidos"""

media_bugs_corrigidos = df["Bugs Corrigidos"].mean()
media_bugs_corrigidos
print(f"Média Diária de Bugs Corrigidos: {media_bugs_corrigidos:.2f}")

"""# Calculando o Total de Tarefas Concluídas"""

total_tarefas_concluidas = df["Tarefas Concluídas"].sum()
total_tarefas_concluidas

print(f"Total de Tarefas Concluídas: {total_tarefas_concluidas}")

"""# Calculando a Média Diária de Tarefas Concluídas"""

media_tarefas_concluidas = df["Tarefas Concluídas"].mean()
media_tarefas_concluidas

print(f"Média Diária de Tarefas Concluídas: {media_tarefas_concluidas:.2f}")

"""# Calculando a Produtividade Diária"""

df["Produtividade Diária"] = df["Tarefas Concluídas"] / df["Horas Trabalhadas"]
df["Produtividade Diária"]

print("Produtividade Diária calculada como o número de tarefas concluídas por hora trabalhada.")

"""# Visualizações Gráficas

## Gráfico de Barras para Horas Trabalhadas, Bugs Corrigidos e Tarefas Concluídas por Dia
"""

plt.figure(figsize=(12, 8))
plt.subplot(3, 1, 1)
sns.barplot(x="Dia", y="Horas Trabalhadas", data=df)
plt.title("Horas Trabalhadas por Dia")

plt.figtext(0.5, 0.9, "Gráfico de Barras mostrando as Horas Trabalhadas por Dia", ha="center")


plt.subplot(3, 1, 2)
sns.barplot(x="Dia", y="Bugs Corrigidos", data=df)
plt.title("Bugs Corrigidos por Dia")

plt.figtext(0.5, 0.6, "Gráfico de Barras mostrando os Bugs Corrigidos por Dia", ha="center")

plt.subplot(3, 1, 3)
sns.barplot(x="Dia", y="Tarefas Concluídas", data=df)
plt.title("Tarefas Concluídas por Dia")

plt.figtext(0.5, 0.3, "Gráfico de Barras mostrando as Tarefas Concluídas por Dia", ha="center")

plt.tight_layout()
plt.show()

"""# Gráfico de Linha para Produtividade Diária


"""

plt.figure(figsize=(10, 6))
sns.lineplot(x="Dia", y="Produtividade Diária", data=df, marker="o")
plt.title("Produtividade Diária (Tarefas Concluídas por Hora)")
plt.xlabel("Dia")
plt.ylabel("Produtividade Diária")
plt.grid(True)

# Adicionando uma caixa de texto explicativa
plt.figtext(0.5, 0.01, "Gráfico de Linha mostrando a Produtividade Diária", ha="center")

plt.show()

"""# Apresentação dos Resultados"""

print(f"Total de Horas Trabalhadas: {total_horas_trabalhadas}")
print(f"Média Diária de Horas Trabalhadas: {media_horas_trabalhadas:.2f}")
print(f"Total de Bugs Corrigidos: {total_bugs_corrigidos}")
print(f"Média Diária de Bugs Corrigidos: {media_bugs_corrigidos:.2f}")
print(f"Total de Tarefas Concluídas: {total_tarefas_concluidas}")
print(f"Média Diária de Tarefas Concluídas: {media_tarefas_concluidas:.2f}")

insights = """
A análise dos dados de produtividade da equipe de desenvolvimento ao longo de uma semana revela alguns pontos importantes:
- O total de horas trabalhadas ao longo da semana foi de {total_horas_trabalhadas}, com uma média diária de {media_horas_trabalhadas:.2f} horas.
- A equipe corrigiu um total de {total_bugs_corrigidos} bugs, com uma média diária de {media_bugs_corrigidos:.2f} bugs corrigidos.
- Foram concluídas um total de {total_tarefas_concluidas} tarefas, resultando em uma média diária de {media_tarefas_concluidas:.2f} tarefas concluídas.
- A produtividade diária, medida como o número de tarefas concluídas por hora trabalhada, variou ao longo da semana, indicando possíveis flutuações na eficiência da equipe.

Esses dados permitem identificar dias de maior e menor produtividade, possibilitando uma análise mais aprofundada das causas dessas variações e a implementação de melhorias no processo de desenvolvimento.
"""

print(insights.format(
    total_horas_trabalhadas=total_horas_trabalhadas,
    media_horas_trabalhadas=media_horas_trabalhadas,
    total_bugs_corrigidos=total_bugs_corrigidos,
    media_bugs_corrigidos=media_bugs_corrigidos,
    total_tarefas_concluidas=total_tarefas_concluidas,
    media_tarefas_concluidas=media_tarefas_concluidas
))

"""# Considerações Finais


*   Cada bloco de código é seguido por um cálculo específico e um comentário explicativo.
*   Gráficos foram gerados e seguidos por uma explicação textual.
*   Resultados são apresentados de maneira clara e organizada.



*Este notebook deve ser executado em Google Colab ou Jupyter Notebook para melhor visualização e organização dos resultados.*
"""